// <auto-generated />
using System;
using KaraokeParty.DataStore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KaraokeParty.Migrations
{
    [DbContext(typeof(KPContext))]
    [Migration("20230114022159_AddPerformanceStatus")]
    partial class AddPerformanceStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KaraokeParty.DataStore.Party", b =>
                {
                    b.Property<int>("PartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartyId"));

                    b.Property<DateTime>("DateTimeCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<string>("PartyKey")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("PlayerState")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("PartyId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("KaraokeParty.DataStore.Performance", b =>
                {
                    b.Property<int>("PerformanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PerformanceID"));

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("PartyId")
                        .HasColumnType("integer");

                    b.Property<int?>("SingerId")
                        .HasColumnType("integer");

                    b.Property<string>("SongFileName")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("PerformanceID");

                    b.HasIndex("PartyId");

                    b.HasIndex("SingerId");

                    b.HasIndex("SongFileName");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("KaraokeParty.DataStore.Singer", b =>
                {
                    b.Property<int>("SingerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SingerId"));

                    b.Property<bool>("IsDj")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("PartyId")
                        .HasColumnType("integer");

                    b.HasKey("SingerId");

                    b.HasIndex("PartyId");

                    b.ToTable("Singers");
                });

            modelBuilder.Entity("KaraokeParty.DataStore.Song", b =>
                {
                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FileName");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("KaraokeParty.DataStore.Performance", b =>
                {
                    b.HasOne("KaraokeParty.DataStore.Party", "Party")
                        .WithMany("Queue")
                        .HasForeignKey("PartyId");

                    b.HasOne("KaraokeParty.DataStore.Singer", "Singer")
                        .WithMany()
                        .HasForeignKey("SingerId");

                    b.HasOne("KaraokeParty.DataStore.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongFileName");

                    b.Navigation("Party");

                    b.Navigation("Singer");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("KaraokeParty.DataStore.Singer", b =>
                {
                    b.HasOne("KaraokeParty.DataStore.Party", null)
                        .WithMany("Singers")
                        .HasForeignKey("PartyId");
                });

            modelBuilder.Entity("KaraokeParty.DataStore.Party", b =>
                {
                    b.Navigation("Queue");

                    b.Navigation("Singers");
                });
#pragma warning restore 612, 618
        }
    }
}
