version: '3.8'

services: 

  db:
    image: postgres
    environment: 
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_DEV_PORT}:5432

  yt_dlp:
    build: ./YoutubeDownload
    ports:
      - 5000:5000
    volumes:
      - "./Songs:/usr/lib/songs"
      - "./YoutubeDownload:/app"

  api:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./appsettings.Production.json:/app/appsettings.Production.json"