version: '3.7'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
        ports:
            - ${POSTGRES_PORT}:5432

    yt_dlp:
        build: ./YoutubeDownload
        ports:
            - ${YT_DLP_PORT}:5000
        volumes:
            - './Songs:/usr/lib/songs'
            - './YoutubeDownload:/app'

    api:
        build: .
        depends_on:
            - db
        ports:
            - ${API_PORT}:8080
        volumes:
            - './Songs:/app/Songs'
            - './appsettings.Production.json:/app/appsettings.Production.json'
            - './react.Production.js:/app/FrontEndSpa/react-env.js'
