export const downloadMessages = [
	"We're listening to your song to see if it's any good...",
	"Checking this song to see if it's worthy of your awesomeness...",
	'I love this song!  Good choice! Hang tight while I jam out...',
	'You can sing this song?  You got skillz yo...',
	"Oh I can't wait to hear this one... it's gonna rock!...",
	'Wait for it... waaaait foooor iiiiit.....',
	'This is going to be legen ... (wait for it) ... dary!',
	'Karaoke time!!!...',
	'Running this song through the awesomeness filter, stand by',
	'Just a minute...',
	'Removing ads from this song... cause ads suck...',
	'Processing... processing... processing...',
	'Fetching muzic... gathering notes... compiling lyrics...',
	'This song is restricted to amazing singers only... which you are!...',
	'In just a few moments this song will be all yours...',
	'One moment please...',
	'Analying this song for adequate notes',
	'Counting the beats in this song...',
	"Previewing this song to see if it's worth your time...",
	'How about a country song next time?...',
	'How about some broadway musical numbers next time?...',
	"Oh good song! You're gonna rock this!...",
	"Really... you're gonna sing THIS song?...",
	"I'm debating on if I'm gonna let you sing this one...",
	'Get ready to hit those high notes and make this song your own!',
	'Your song request is a true masterpiece. Prepare to blow the audience away!',
	'Are you ready to unleash your inner rockstar with this awesome choice?',
	"Your song request is so catchy, it's practically contagious. Brace yourself for a good time!",
	"You've chosen a classic! Prepare to transport everyone back in time with your incredible performance.",
	"You're about to turn up the volume and bring down the house with this iconic hit!",
	'Your song choice is pure gold! Get ready to shine like a superstar on that stage.',
	'This song is an anthem of empowerment. Get ready to inspire the crowd with your incredible rendition!',
	'Your performance is going to be legendary, just like the artist who made this song famous!',
	"Get ready to dance like nobody's watching and sing like you're on top of the world!",
	"With this song, you'll be the life of the karaoke party. Prepare for a standing ovation!",
	"Your request is straight from the pop-culture hall of fame. You're about to make memories!",
	'Ready to channel your inner diva? Get ready to dazzle the crowd with your incredible talent!',
	'Your song choice is a crowd-pleaser! Brace yourself for a night of pure fun and entertainment.',
	'Break a leg and break some records with your unforgettable performance of this chart-topper!',
	'Warning: Singing this song may cause uncontrollable toe-tapping and spontaneous dance moves!',
	'Your request just made our playlist 10 times cooler. Prepare to rock the stage like a true legend!',
	'Get ready to shine brighter than the disco ball with this timeless karaoke favorite!',
	'Your choice is a true gem. Get ready to own the stage and deliver an unforgettable performance!',
	"You've picked a song that's both fun and full of nostalgia. Get ready to make everyone smile!",
	'Calling all fans! Prepare to transport everyone to a galaxy far, far away with this epic tune.',
	'Your request is a guaranteed mood-lifter. Get ready to bring joy to the entire room!',
	"You're about to make the crowd laugh, cry, and sing along with this heartfelt song choice.",
	'This song is a testament to resilience and strength. Prepare to inspire everyone with your rendition!',
	'Your choice is like a musical time machine. Get ready to take the audience on a trip down memory lane!',
	'Ready to embrace your inner pop idol? Prepare for a night of stardom and sing your heart out!',
	'Your song request is an absolute banger. Get ready to bring the house down with your killer performance!',
	'Warning: Singing this song may cause spontaneous dance-offs and unstoppable sing-alongs!',
	'Prepare to step into the spotlight and become the karaoke champion with this legendary song choice.',
	'Your request is a testament to your impeccable taste in music. Get ready to show off your skills and have a blast!',
	'Congratulations! Your song choice is a karaoke favorite. Get ready to create unforgettable memories!',
	'Your request is a crowd-pleaser. Prepare for a night of singing, laughter, and pure joy!',
	'Get ready to take center stage and serenade the crowd with your powerful rendition of this timeless classic.',
	'Your song request is the ultimate feel-good anthem. Get ready to spread positivity and good vibes!',
	'Brace yourself for a standing ovation! Your song choice is going to leave everyone in awe.',
	'Get ready to channel your inner superstar and bring down the house with this iconic hit!',
	'Your choice is like a musical time capsule. Prepare to transport everyone back to a golden era of music!',
	"Calling all fans of this artist! It's time to shine and show the world your love for their incredible music.",
	"With this song, you'll be the karaoke king/queen of the night. Get ready to own that stage!",
	'Warning: Singing this song may result in an outbreak of infectious dance moves and unstoppable sing-alongs!',
	'Your request is a true gem. Prepare for a night of unforgettable performances and good times.',
	'Get ready to unleash your inner performer and make this song your own. The spotlight is waiting for you!',
	'Your song choice is like a shot of pure happiness. Get ready to uplift the crowd and create magical moments!',
	'This song is an absolute crowd-pleaser. Prepare to make friends, strangers, and everyone in between sing along with you!',
	'Your request is a powerful anthem of self-expression. Get ready to inspire others with your incredible performance.',
	"Brace yourself for a night of laughter and entertainment! Your song choice is sure to bring smiles to everyone's faces.",
	'Ready to make history? Prepare to leave a lasting impression with your show-stopping performance of this iconic tune.',
	'Your song request is like a time machine to the golden age of music. Get ready to transport everyone back in time!',
	'This song is the perfect choice to showcase your vocal range. Get ready to hit those high notes and impress the crowd!',
	'Your request is like a burst of energy. Get ready to ignite the stage and create a memorable karaoke experience for all!',
	'That was an amazing performance! How about requesting a catchy pop song for your next choice? Get ready to make everyone dance along!',
	'Great choice! Next time, why not try a classic rock anthem? Unleash your inner rockstar and blow us all away!',
	"Your song choice was brilliant! Consider requesting a beautiful ballad for your next performance. Let your emotions soar and touch everyone's hearts!",
	'You nailed that tune! How about switching it up next time and requesting a fun and energetic disco hit? Get ready to boogie the night away!',
	"Interesting choice...Now, let's embrace some soulful vibes. Request a smooth R&B song for your next choice and captivate us with your incredible voice!",
	"You're gonna bring the house down with that song! How about requesting a show-stopping Broadway musical number for your next performance?",
	'Your performance will be electrifying! Next time, consider requesting a catchy hip-hop track. Get ready to drop some killer rhymes and own the stage!',
	"You're gonna absolutely slayed that song! Now, let's transport ourselves to the tropics. Request a lively reggae tune for your next choice and let the good vibes flow!",
	"You're going to wow us with your talent! How about requesting a heartwarming country song for your next performance? Embrace the twang and create some unforgettable moments!",
];
